sudo: required
language: node_js
node_js:
- '8'
before_install:
- echo "${SOMEVAR}"
- sh ./test.sh
- openssl aes-256-cbc -K $encrypted_e09ddef386b2_key -iv $encrypted_e09ddef386b2_iv
  -in super_secret.txt.enc -out super_secret.txt -d
script:
- cat super_secret.txt
after_success: 
env:
  global:
    - CAMPFIRE_TOKEN=abc123
    - secure: I6aqilh4jG2At9bs3SJXwQLox0TDGhLkW3nJJzic7rSqvBtASyZgGKQBtbY8gntcQJQIBhWEQ/ZGreaNJ5IEyPcjtjrZhKuQV63spE5peEZhQzwaopMlamhSo8Yswh7SsXJx33Xc7mRwvUXO6E7ZKgUxCipH1yjUwTAoqFOo67LeY9RnGjg27iu/9koreMhenX9FC9JutWRBWFTUsNKUPIdY/gHjQNSZYTRdwof3aZ5fX3qCytSClo6nOuCYwVgxaIvVClx56UtWMqNRUNaQzYc6hFS41VxPy1x0qxgRRnBViU4Va8Yl0YcfN370hbrIJhEjJshK2ly6RJ8cZtM40Pevx1lkRXRYjSUXdNNmHlJLsljBD2Yaqd8/IUBaG+V4V3RcasondC66NisTg/LTILqlQBUQgZLBRFEG+m9ttMxj/9QVeK4eHhLpiJc2Ffe/N5gtkts0d9/oiJmQiV2+O6iuscrCvLfrAuy6u/rAe/vu69S+N7BMvwc2CMrGmdgU1vVwntZ0lc7P63NZUMiM5Q5FCsst4mnVFtGF9ihIHYg7K9AqBVVR3K9xIf7WvPAhvfwQkzXadpqJfmJ4vWwdD9mGltbQo3yHw/seidUDL9fFjpgMIm1DHOHpfgTRdFpSGx3QxQ+KmZWsJqgkh+uKb1jzFTiEzFD0lDigIEcxW3o=
