sudo: required
language: node_js
node_js:
- '8'
env:
  global:
    secure: U62Bp1uLHsS4G4FDdSUPaGRHp6rv27Jy54jW8UJ5Pc8k0Q36l5M7MPN0O19JUTZr1SV2VmElsDKoSu2Dkkkdgg0oW0ctqaytissLCKGmeCCmWOF52YaJJUHzmqpWHsnlSr5/zeP10KRoWoU72L98btNYJimLXBoJNxkw5B+aYYducqdNHu/vn+3K/R/R7UKRSy1r3mqYmk5WfUM1mPenR9wDzjP7ltS06Z4VCkpYztqT+wC+anfMRliE9eA8h7NRlmgWEIXGEyOe7H+b308XsZG48/gkxxOX4iEDKQU/tI9JBeKKwLMqzkL1fQn4vSJxS1HRbkwuos4fzUc+jgeKXGU7NGCbYrUSzMAXmyDUMiJBEshcTcCD8ASHjwfyoE0wzeteaKJfN0Kb9UguoA+PTY28FGFRp+dou8acdyCYCNYlAcPAA37ZDZGh7WJ8SsHp6MCPhcc4LclkUKWtLp+FRlPgaGuUoD4OSSDJPKLVdj5XM3rxoW76ixkcmdpOG2p9ERIhyHKG7tZbJnLqLqyIh94NDqgdaWIwoomg8AOXb3WIt9nMrFUicrGoKdNNBd/Tr2NupsMhdI6ASqBz6lu+kSJf25qqxdWMcbNkDLgbUZO1z6LGiIamnk2VjPTXsJY/1jyIq8gOqhhDcufS39HjfH5w6Um9LApDKCqGuTqVnbs=
before_install:
- echo "${SOMEVAR}"
- sh ./test.sh
- openssl aes-256-cbc -K $encrypted_e09ddef386b2_key -iv $encrypted_e09ddef386b2_iv -in super_secret.txt.enc -out super_secret.txt -d
script:
- cat super_secret.txt
after_success: 
