sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
notifications:
  slack: ibm-security:qnST3ooBK8sbzusQPaGIuLuQ
before_install:
- openssl aes-256-cbc -K $encrypted_e09ddef386b2_key -iv $encrypted_e09ddef386b2_iv -in super_secret.txt.enc -out super_secret.txt -d
- echo "${SOMEVAR}"
- sh ./test.sh
script:
- cat super_secret.txt
after_success: 
